### ISSUE TITLE
Question about optional fields implementation

### ISSUE THREAD

**Issue by sheriffderek** [hhff/ember-chimp#3]
Question about optional fields implementation.

Hello!

I'm trying to get 'name' as well as 'email.' So far, we only get the email in the system. Any suggestions?

```
<label>
  <div class="label-text">Name</div>
  {{input key-press="valueDidChange"
          placeholder="Barack Obama"
          value=firstname
          type="text"
          name="FIRSTNAME"}}
</label>

<label>
  <div class="label-text">Email</div>
  {{input key-press="valueDidChange"
          placeholder="email@address.domain"
          value=value
          type="email"
          name="EMAIL"}}
</label>

{{#if chimpSays}}
  <div class="chimp-says">{{chimpSays}}<span class='alert-star'>*</span></div>
{{/if}}
```

**Comment by hhff** [comment]
hmm - looks fine to me 👍 

We're just using jquery's `serializeArray` to pack up the form data.
https://github.com/hhff/ember-chimp/blob/master/addon/components/ember-chimp.js#L163

Can u see the FIRSTNAME property going up in the request?

**Comment by sheriffderek** [comment]
The FIRSTNAME wasn't showing up in mail-chimp, but maybe it because that field isn't created... I didn't have time to follow up. I'll close this, and reopen or let you know what I find later. Thanks.
