### ISSUE TITLE
readme "action" is wrong

### ISSUE THREAD

**Issue by sethbrasile** [hhff/ember-chimp#4]
In the `ember-chimp` component:

    if (this.get('didSubmitAction')) { this.sendAction('didSubmitAction', request); }

In the readme:

    {{ember-chimp formAction="//your.mailchimp.form.action"
              action="emberChimpDidSubmit"}}

Readme should be:

    {{ember-chimp formAction="//your.mailchimp.form.action"
              didSubmitAction="emberChimpDidSubmit"}}

I will submit a PR if I can find the time! 😄

**Comment by hhff** [comment]
oh!  Good catch - looks like a typo!
